INSERT INTO USUARIO (ID, NOME, LOGIN, SENHA, EMAIL, SITUACAO) VALUES (1, 'FELIPE', 'FELIPE@GMAIL.COM', '12345', 'FELIPE@GMAIL.COM', 'ATIVO');
ALTER SEQUENCE USUARIO_ID_SEQ RESTART WITH 2;
INSERT INTO PERFIL(ID, DESCRICAO) VALUES (1, 'Administrador');
INSERT INTO PERFIL(ID, DESCRICAO) VALUES (2, 'Gerente');
INSERT INTO PERFIL(ID, DESCRICAO) VALUES (3, 'Cliente');

INSERT INTO RECURSO(ID, NOME, CHAVE) VALUES (1, 'Tela Usuário', 'usuario');
INSERT INTO RECURSO(ID, NOME, CHAVE) VALUES (2, 'Tela Perfil', 'perfil');
INSERT INTO RECURSO(ID, NOME, CHAVE) VALUES (3, 'Tela Recurso', 'recurso');

ALTER SEQUENCE PERFIL_SEQ RESTART WITH 4;

